site_name: SSMP5 Docs
site_url: https://docs.sillysmp.net
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.footer
  palette: 
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: light blue
      accent: pink
  
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: light blue
      accent: pink

use_directory_urls: true
extra:
  social:
    - icon: simple/youtube
      link: https://youtube.com/@SyddersLMAO
  cname: docs.sillysmp.net

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true